// Values from portable `.ccnvs` documents are untrusted. Claude agents are
// launched by typing a command into a shell, so only fixed-format fields may
// reach that command line.

/** Claude session identities are UUIDs generated by ccanvas. */
export function safeClaudeSessionId(value: string | undefined): string | undefined {
  return value && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)
    ? value
    : undefined
}

/** Claude model aliases/ids contain no shell syntax. */
export function safeClaudeModel(value: string | undefined): string | undefined {
  return value && /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(value) ? value : undefined
}

/** Remove characters that are special inside a double-quoted shell word. */
export function shellSafeTitle(value: string | undefined): string {
  return (value ?? '').replace(/["`$\\!]/g, '').replace(/[\u0000-\u001f\u007f]/g, ' ').trim().slice(0, 120)
}
